apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cwdd-eks-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-008df4645bcb7fc91 }
      us-east-1b: { id: subnet-0f34d43cdf920ff72 }

nodeGroups:
  - name: cwdd-eks-ng-1-X86
    labels: { arch: x86 }
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true
  - name: cwdd-eks-ng-2-ARM64
    labels: { arch: arm64 }
    instanceType: t4g.small
    desiredCapacity: 1
    privateNetworking: true
